### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by bincat233** [anselmwang/obsidian-vim-multibyte-char-search#1]
When I press `<space>n` , it shows "Complex char to simple char dict is not ready yet."

The `.obsidian/plugins/obsidian-vim-multibyte-char-search` only have two files: `main.js` and `manifest.json`. The `pinyin_search.dict.txt` has not install automatically.

**Comment by anselmwang** [comment]
@RRRRRm , so sorry about that. I have released a [new version](https://github.com/anselmwang/obsidian-vim-multibyte-char-search/releases/tag/1.0.4). Obsidian doesn't discover the new version 1.0.4 yet.
![image](https://user-images.githubusercontent.com/7410579/164749001-e86975e2-9d7e-4201-911f-c1b9bf1fbc48.png)

 If you want to fix it right now, you can download the "pinyin_search.dict.txt" for that page manually and put it into "{your note folder}\.obsidian\plugins\obsidian-vim-multibyte-char-search\"

BTW, I have to admit I am not actively using this plugin right now. I find it is easier to change the input method to search for Chinese characters directly right. Would love to know your experience.

**Comment by bincat233** [comment]
> I find it is easier to change the input method to search for Chinese characters directly right. Would love to know your experience.

Yes, I agree with you. But I still want to try your plugin. Because it is so cool !!! ╰(￣▽￣)╭
